const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'Free-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popolar shirt',
    },

    {
      name: 'Fit Shirt',
      slug: 'Fit-shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Addidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popolar shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.2,
      numReviews: 15,
      countInStock: 10,
      description: 'A popolar Slim shirt',
    },
    {
      name: 'Golf-Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Richman',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart Looking Pants',
    },
    {
      name: 'Causal-Pants',
      slug: 'causal-Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 90,
      brand: 'Zara',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart Looking Pants',
    },
  ],
};

export default data;
