/*eslint-disable @next/next/no-img-element */

import Head from 'next/head';
import Link from 'next/link';
import { Store } from '../utills/Store';
import React, { useContext } from 'react';

export default function Layout({ title, children }) {
  const { state } = useContext(Store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>{title ? title + '-E-Shopt' : 'ecommerce'}</title>
        <meta name="description" content="Content Generated by Next App" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between bg-stone-50 ">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between  shadow-md">
            <Link href="/">
              <a className=" text-lg font-bold">E-Shop</a>
            </Link>

            <div>
              <Link href="/cart">
                <a className="p-2 text-sm">
                  Cart
                  {cart.cartItems.length > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white ">
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                </a>
              </Link>
              <Link href="login">
                <a className="">login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          Footer
        </footer>
      </div>
    </>
  );
}
